Екі 3×3 матрица құрып, олардың қосындысын, айырмасын және көбейтіндісін табыңыз.

In [3]:
import numpy as np
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[4,2,1], [5,7,6], [3,5,8]])
C = A+B
D = A-B
E = np.dot(A,B)
print(C)
print(D)
print(E)

[[ 5  4  4]
 [ 9 12 12]
 [10 13 17]]
[[-3  0  2]
 [-1 -2  0]
 [ 4  3  1]]
[[ 23  31  37]
 [ 59  73  82]
 [ 95 115 127]]


3 өлшемді екі вектордың скаляр көбейтіндісін және олардың арасындағы бұрышты есептеңіз.

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
cos_sim = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
print(c)
print(cos_sim)

32
0.9746318461970762


Берілген матрицаның детерминантын, кері матрицасын және өз мәндерін табыңыз.

In [5]:
A = np.array([[3,2,2], [1,3,1], [5,3,4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigvals = np.linalg.eig(A)
print(det)
print(inv)
print(eigvals)

5.000000000000002
[[ 1.8 -0.4 -0.8]
 [ 0.2  0.4 -0.2]
 [-2.4  0.2  1.4]]
EigResult(eigenvalues=array([7.7647666 , 0.33971392, 1.89551948]), eigenvectors=array([[-0.46785123, -0.54414157,  0.17328125],
       [-0.27450412, -0.10820096, -0.74261081],
       [-0.84009684,  0.83198708,  0.64691792]]))


np.random.randn() арқылы 1000 элементтік үлгі алыңыз және орташа, дисперсия мен стандартты ауытқуды есептеңіз.

In [8]:
samples = np.random.randn(1,1000)
mean = np.mean(samples)
var = np.var(samples)
std = np.std(samples)
print(mean)
print(var)
print(std)



-0.0014723953810881483
0.9757453508389754
0.9877982338711562


Берілген тізім: [5, 10, 15, 20, 25] — үшін Min-Max және Z-score нормализациясын орындаңыз.

In [15]:
data = np.array([5, 10, 15, 20, 25])
#var = np.var(data)
#std = np.std(data)
min_max = (data - np.min(data))/(np.max(data) - np.min(data))
z_score = (data - np.mean(data))/np.std(data)
print(min_max)
print(z_score)

[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
