# Python-дағы ОББ, ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттер, NumPy кіріспе (массивтер, векторизация, негізгі операциялар)

1. Мақсат                                                                        
Python тілінде объектілі-бағытталған бағдарламалау (ОББ), ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттермен жұмыс, сондай-ақ NumPy кітапханасындағы негізгі операцияларды меңгеру.

# Есеп 1.1:

---
Кітап (Kitap) атты класс құрыңыз. Бұл кластың атауы (atau) және авторы (avtory) деген екі атрибуты болуы керек.\
__init__ әдісін қолданып, кітап атауын және авторын инициализациялаңыз.\
Класс ішінде кітап_туралы_мәлімет (kitap_turaly_malimet) атты әдіс жасаңыз. Бұл әдіс "Кітап: [Атауы], Авторы: [Авторы]" деген мәтінді консольға шығаруы керек.\
Осы класстан бір нысан (объект) жасаңыз және кітап_туралы_мәлімет әдісін шақырыңыз.

In [6]:
class Kitap:
  def __init__(self, atau, avtory):
    self.atau = atau
    self.avtory = avtory

  def kitap_turaly_malimet(self):
    print(f"Кітап: {self.atau}, Авторы: {self.avtory}")

Kitap_ = Kitap("Алхимик", "Пауло Коэльо")

# Әдісті шақыру
Kitap_.kitap_turaly_malimet()

Кітап: Алхимик, Авторы: Пауло Коэльо


# Есеп 2.1:

---

numpy кітапханасын np ретінде импорттаңыз.\
1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз.\
3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз. Мысалы, 1-ден 9-ға дейінгі сандарды пайдаланыңыз.\
Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз.

In [1]:
import numpy as np
arr_a = np.arange(1, 10)
arr_b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_a)
print(arr_b)
print(arr_a.shape)
print(arr_b.shape)
print(arr_a.dtype)
print(arr_b.dtype)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)
int64
int64


# Есеп 3.1:


---

numpy-ді np ретінде импорттаңыз.\
Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін (vec1 және vec2) жасаңыз (мысалы, 1-ден 10-ға дейінгі).\
Векторизацияны қолдана отырып (циклсіз):
- Екі массивті қосыңыз (vec1 + vec2).
- Әрбір элементтің квадратын есептеңіз (vec1 ** 2).
vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз.\

Барлық нәтижелерді консольға шығарыңыз.

In [10]:
import numpy as np

vec1 = np.random.randint(1, 10, size=5)
vec2 = np.random.randint(1, 10, size=5)

sum = vec1 + vec2

squared_vec = vec1 ** 2

mean_vec1 = vec1.mean()
max_vec1 = vec1.max()

print(f"vec1: {vec1}")
print(f"vec2: {vec2}")
print(f"vec1 + vec2: {sum}")
print(f"vec1 квадраттары: {squared_vec}")
print(f"vec1 орташа мәні: {mean_vec1}")
print(f"vec1 ең үлкен мәні: {max_vec1}")

vec1: [4 9 2 3 9]
vec2: [1 8 7 4 1]
vec1 + vec2: [ 5 17  9  7 10]
vec1 квадраттары: [16 81  4  9 81]
vec1 орташа мәні: 5.4
vec1 ең үлкен мәні: 9
